"""added-auth-otp-fields

Revision ID: 70d8ef833061
Revises: 163269334c08
Create Date: 2026-05-08 15:41:24.675738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d8ef833061'
down_revision: Union[str, Sequence[str], None] = '163269334c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('otp', sa.Integer(), nullable=True))
    op.add_column('auth', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'otp_expires_at')
    op.drop_column('auth', 'otp')
    # ### end Alembic commands ###
